name: face_duldul
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.24.3
  - opencv=4.10.0
  - keras=2.15.0
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - tqdm=4.66.4
  - pip
  - pip:
    - dlib==19.24.4

    ## 실행코드 : conda env create -f environment.yml